### PR TITLE
2022 recommended budget

### PR DESCRIPTION
**Pull request by derekeder**
Update the data with the 2022 recommended budget by Oak Park Village. Also updates the years referenced in several places in the text.

### CODE REVIEW

**Comment by achastain** [comment]
At the top level there is an item without a label. I think it might be a new item this year as it has a $0 value for 2013-2019 and no entry for 2020 or 2021. Its 2022 value is $1,396,366. I can’t find it in the spreadsheet on its own, so maybe it's a total? When I expand the item, it has the description for the Health Insurance Fund, but then the "Breakdown by Department" button doesn't go to another page.
Screen Shot 2021-11-07 at 2 41 48 PM
Screen Shot 2021-11-07 at 2 50 37 PM

**Comment by achastain** [comment]
**Developer Customer Services department**
Within the [General Fund](https://deploy-preview-17--budget-oak-park.netlify.app/#?year=2022&figures=nominal&breakdown=Fund&filter_1=general-fund), DCS - Neighborhood Services and DCS - Permit Processing are listed twice. 

DCS - Neighborhood Services
The first amount is $1,363,784 and the other amount is $100. Combined, these are the correct 2022 total for the division. 

The DCS - Permit Processing 
$1,553,850 and $25,500 are the 2 totals listed. Combined, these are the correct 2022 total for the division.

Screen Shot 2021-11-07 at 3 41 45 PM

**Comment by achastain** [comment]
**Human Resources Department** within the [General Fund](https://deploy-preview-17--budget-oak-park.netlify.app/#?year=2022&figures=nominal&breakdown=Fund&filter_1=general-fund&filter_2=41090)
There are several things going on with this department and I'm not sure if they are all related to each other or not.
1. The department is listed twice in the General Fund.
2. The totals in the collapsed rows ($447,204 and $9,021,242) don't match what is in their interior graphs show ($72,204 and $707,475). FWIW, the interior graphs total up to the actual total in the budget ($779,679).
Screen Shot 2021-11-07 at 4 03 06 PM

**Comment by achastain** [comment]
**Health Services** is also mentioned twice in the [General Fund](https://deploy-preview-17--budget-oak-park.netlify.app/#?year=2022&figures=nominal&breakdown=Fund&filter_1=general-fund)

1. The two amount ($3,773 and $906,858) total up to the department total ($910,631).
2. The other quirk is that the graph on the smaller amount, is showing the larger dollar amount. Also, sometimes both graphs aren't there. I can't pinpoint why. I don't know if it's because I am sorting the table by department name and that is throwing something off. Steps to reproduce (I think):
1. View home page. Expand General Fund. Click button to "View Departments".
2. Sort General Fund by Department (A to Z).
3. Expand 1st Health Department entry  for $3,773. It shows the correct graph. Leave this section open.
4. Expand the 2nd Health Department entry for ~ $900k. Section expands and shows no graph and the other section updates to show the $990k graph.

I am seeing this exact same thing with Human Resources, which also has 2 entries in the table.

Screen Shot 2021-11-07 at 4 40 23 PM


Screen Shot 2021-11-07 at 4 46 54 PM

**Comment by achastain** [comment]
**Affordable Housing** and **ARPA FUNDS**
The FY 2022 budget has 2 new funds: one each for Affordable Housing and the ARPA funds. Neither are showing up individually that I can find. Both are kind of a big deal, but I'm not sure why they aren't showing up in the hierarchy. I just want to call that out in case there is some quirk that it causing it.

**Comment by derekeder** [comment]
I updated the import script to pull in the 2022 budget data & descriptions first. This resolved the rows with the missing titles and hopefully most of the others too

**Pull request merged**
