### PR TITLE
update with 2023 adopted budget

### PR DESCRIPTION
**Pull request by derekeder**
Updates the Village of Oak Park with budget data from the 2023 adopted budget. This includes actuals for 2020 and 2021, as well as estimates for 2023. Also updates the CPI index for adjusting for inflation

Still to do:
* [ ] confirm the numbers look correct and add up as expected
* [ ] add fund description for the American Rescue Fund

### CODE REVIEW

**Comment by achastain** [comment]
I've gone through all the updated years. I'll make comments based on year.

**2023**

1. Within the General Fund, the DPW-Building Maintenance appears twice. One amount for $1,286,868 and the second for $178,000. If I click on the smaller one, the site takes me to the breakdown for the big one. It looks like the $178k is a single line item that isn’t getting combined with everything else for the department. Maybe the $178k should be combined with the other?

2. There was one item at the top level that looked like it should be within a department. That was: **Travel, Training, Wellness ($150,000)** This looks like a single line item that should be in the Village Manager’s office instead of at the top of the budget. But maybe it’s coded in a weird way in the budget.

**Comment by achastain** [comment]
**2021 and 2022 Parking Fund**
I accidentally included an extra line item in the spreadsheet. I'm sorry about that. It is the ARPA transfer into the Parking Fund which is income, not an expense. This is skewing the expenses for those two years. I think it is line 2392 in the cleaned version of the spreadsheet. I've attached a screenshot showing the row to be removed. The amounts that need to be removed are:
2021 | -3492876
2022 | -2632423

Screen Shot 2023-01-28 at 5 11 11 PM

**Comment by achastain** [comment]
**2021 and 2022 Sustainability Fund**
It looks like the Sustainability Fund has two line items that got merged and, in doing so, it lost the 2021 and 2022 values. I think that was the office supplies and operational supplies got merged.
Line 1044 in the cleaned spreadsheet (highlighted in yellow in the attached screenshot) shows **Office Supplies**. The original budget (highlighted in blue) shows office supplies AND operational supplies. 

I think the fix is to:
1. Add office supplies values for:
2021 | 707
2022 | 1200
2023 | 1200 (change from 26700)
2. Add a new line item to the spreadsheet for operational supplies. It only has a value for 2023. 
2023 | 25500
 

cleaned-vs-budget

fix-and-add

**Comment by achastain** [comment]
I have copy to use for the American rescue fund and the affordable housing fund.

**American rescue fund**
The American Rescue Plan Act of 2021 is a federal program that provides money to local governments to address the continued impact of COVID-19. Oak Park received $38,984,402 in aid from this program.

**Affordable Housing Fund**
During Fiscal Year 2022, the Village Board enacted the Housing Trust Fund Ordinance, which established the Housing Trust Fund which provides sustainable financial resources to address the affordable housing needs of eligible households in Oak Park.

**Comment by derekeder** [comment]
@achastain cool. data updated and I added in the descriptions. the preview is also updated.

I have a part of my cleanup script that checks for the expected totals. It looks like 2021, 2022 and 2023 are off still:

Actuals 2021: 146703249 : sum is incorrect
  off by -34723
Actuals 2020: 151218743 : sum is incorrect
  off by -22278
Estimates 2023: 199453326 : sum is correct
Estimates 2022: 171848484 : sum is incorrect
  off by -39200

**Comment by achastain** [comment]
Good news. I think I found the discrepancies and I think there two rows in the spreadsheet that aren't getting summed for some years. But first, the overall totals I originally gave you are off. I needed to get those numbers straight to figure out how 2020, 2021, and 2022 were off.

**UPDATED TOTALS**
When we took out the ARPA line item, that changed the overall totals for 2021 and 2022. The totals should be:
2020 Actual    | 151,218,743
2021 Actual     | 146,703,249
2022 Estimate | 171,848,484
2023 Estimate | 199,453,326

**CAPITAL IMPROVEMENT FUND**
This fund is responsible for most of the shortfall. It looks **line 1368** isn’t getting counted for 2020, 2021, and 2022. That one line item has expenses equal to each year’s missing amount.

YEAR   | SUM             | BUDGET       | FUND OFF BY
2020   |    7,610,864  |    7,633,142   | -22,278
2021   |    8,196,892  |    8,230,908  | -34,016
2022   |  13,635,103  | 13,673,103    | -38,000

line1368

**SUSTAINABILITY FUND**
I think the remainder of the shortfall is in the Sustainability Fund. It looks **line 1310** isn’t getting counted for 2021 and 2022. That one line item has expenses equal to each year’s missing amount. This row has the same office supplies amount we were dealing with earlier.
YEAR  | SUM             | BUDGET       | FUND OFF BY
2021   |    318,719     |    319,426      |   -707
2022   | 1,245,407    | 1,246,607      | -1200

line1310

**Comment by achastain** [comment]
@derekeder, I also found another mistake on my part (sorry). There are several DPW ‐ Fleet Operations line items with FundID=1. These all should be FundID=1001. I think this explains why the Public Works budget is divided into 2 chunks.

**Comment by derekeder** [comment]
cool. should i update the numbers on the website again?

**Comment by achastain** [comment]
If you resolved what was going on with those two line items, then the numbers should all have the right totals. I've already started working on adding functions to every line item for 2020,2021,2022, 2023.

**Comment by derekeder** [comment]
ok I think I sorted these issues out - thanks for tracking down these line items. the issue was indeed with lines 1310 and 1368. The reason they weren't counted was because there were lines that had the identical `Fund ID`, `Department ID`, `Program ID`, and `Account ID` combination. The app needs to have a unique combination of those numbers or else it will get skipped. 

I found removing line 1369 and and merging 1311 in with 1310 resolved the issue. I updated the data on my end - could you do the same on the source spreadsheet?

I also changed the percentages to round to the nearest tenth of a percent, which I think makes a clearer picture. You can check it out here: https://deploy-preview-18--budget-oak-park.netlify.app/

**Comment by achastain** [comment]
Woo hoo! It looks great! All the numbers add up :-)
I updated the Google spreadsheet by removing line 1369 and and merging 1311 and 1310. I've also made all the other updates that we discovered along the way. It should be squared away now. The next step is to add the functions. I'm working on that now.

**Comment by derekeder** [comment]
great! i'll go ahead and merge this in and make it live. we can get the functions working in a new pull request.

**Pull request merged**
