### PR TITLE
function view

### PR DESCRIPTION
**Pull request by derekeder**
Adds functionality to view budget items by "Function" and adds tabs to toggle between this view and the existing "Fund" view.

Screen Shot 2023-02-19 at 4 11 52 PM

### CODE REVIEW

**Comment by achastain** [comment]
@derekeder , I made updates to the spreadsheet if you want to pull those over.
1. I added a new tab with descriptions for each function.
2. I updated the pension department names and formatted all the names to use consistent capitalization.

**Comment by derekeder** [comment]
@achastain ok updated the data and appended the Fund name to the Department. Here's that same view:

Screen Shot 2023-02-24 at 4 04 25 PM

What do you think?

**Comment by achastain** [comment]
I like this. I think it makes both the Function and Fund views easier to understand. What do you think of it?

**Comment by derekeder** [comment]
I agree. I think it helps a lot. I ended up showing the full hierarchy for each line item down to the description level. Its a little long for some, but I think makes things easier to understand. I also moved the function/fund buttons to the top to make them a little more distinct and clear.

I still have 2 things I'd like to do before merging this in:
- i need to add in the function descriptions
- there appears to be a bug when switching between estimates and actuals when looking at departments or descriptions

**Comment by derekeder** [comment]
@achastain ok - descriptions added. I also fixed the bug which was introduced because of the new way we're displaying names. I think this is good to go!

**Comment by achastain** [comment]
Yay! I have the updates for the FAQ just about ready. I'll submit a pull request for those.

**Comment by derekeder** [comment]
Great! I'll go ahead and merge this in.

**Pull request merged**
